environment: production
http_addr: :8080

youdao:
  app_id: 55f6b4a5233a7863
  app_key: rlAijgxZuVbSPtUxclB2BgZ5zF0baKpx

cache:
  redis: true
  lru: true

lru:
  size: 1000

redis:
  host: 'redis'
  port: 6379
  db: 1