version: '3'
services: 
    api:
        build: .
        ports:
            - '8080-8081:8080'
        volumes:
            - .:/code
            - ./credentials:/root/.aws/credentials
        command:
            - translator-api
            - serve
            - --config=/code/config.production.yaml
        links:
            - 'redis'
    redis:
        image: 'redis:6'
        volumes: 
            - /data/redis:/data
