version: '3'
services: 
    api:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/code
        command:
            - app
            - --config=/code/config.production.yaml
    redis:
        image: 'redis:6'